import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import { Weight } from "lucide-react";
import FirstNav from "./_component/FirstNav/FirstNav";

const ExoFont = Exo({
  variable: "--font-exo",
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${ExoFont.className} antialiased`}>
      <body className="">
        <FirstNav />
        <Navbar />
        <div className="container mx-auto px-4 md:px-0 xl:max-w-7xl">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
